### ISSUE TITLE
Incorrect behavior with some international settings

### ISSUE THREAD

**Issue by FrenchBear** [qwertie/GraphingCalculator#1]
Hi

First, thanks and nice job with this calculator, I like it!

Unfortunately there is a problem with international settings, for instance when decimal separator is a comma, such as with my French (France) settings.

When you initialize a calculator, you predefine some well-known constants in PrepareCalculators() in CalcForm.cs using:
`var variables = ParseExprs("Variables", $"pi={Math.PI};tau={Math.PI*2};e={Math.E};phi=1.6180339887498948; {cbVariables.Text}");
`
On my system, string interpolation produces
"pi=3,14159265358979;tau=6,28318530717959;e=2,71828182845905;phi=1.6180339887498948; x=1"
Using commas, as specified in my formatting preferences.
But then ParseExprs fails with an exception
"Variables: Unexpected separator: ',' should be ';'\r\npi=3,14159265358979;tau=6,28318530717959;e=2,71828182845905;phi=1.6180339887498948; x=1\r\n----^"

If you don't mind retargeting project to .Net framework 4.6, you can simply use Invariant method of new class FormattableString:
`var variables = ParseExprs("Variables", FormattableString.Invariant($"pi={Math.PI};tau={Math.PI*2};e={Math.E};phi=1.6180339887498948; {cbVariables.Text}"));`
to fix the problem.  Otherwise, you can rewrite it using String.Format providing Invariant culture.

Similar problem in SetRanges function, I would upgrade it to 
`var newRanges = string.Format(System.Globalization.CultureInfo.InvariantCulture, "{0:G8}..{1:G8}; {2:G8}..{3:G8}; {4}", 
                            xRange.Lo, xRange.Hi, yRange.Lo, yRange.Hi, zRangeText);`

to avoid the same problem.

**Comment by qwertie** [comment]
Thanks for bringing this to my attention! I'll try to remember to fix it today.

I always say MS made a mistake in using international formatting as the default. As this case illustrates, worst-case program behavior tends to be much worse for wrongly using international formatting than for wrongly using US-centric formatting.

**Comment by qwertie** [comment]
It seems to be fixed now. Releasing new version.
